"""Add doctor_notes and prescription_path

Revision ID: e3a4242b2b8d
Revises: <REVISION_ID>
Create Date: 2025-11-24 16:36:38.922883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a4242b2b8d'
down_revision = '<REVISION_ID>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prescription_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('skin_records', schema=None) as batch_op:
        batch_op.alter_column('baby_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_records', schema=None) as batch_op:
        batch_op.alter_column('baby_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_column('prescription_path')
        batch_op.drop_column('doctor_notes')

    # ### end Alembic commands ###
